### ISSUE TITLE
Yoast json import results in error 500

### ISSUE THREAD

**Issue by georgegebbett** [georgegebbett/recipe-buddy#10]
On pages such as https://www.joyfulhealthyeats.com/no-bake-vegan-cookie-dough-energy-balls/, the ld-json is added by an SEO plugin called Yoast. This plugin puts the data on the page in a Graph, which is not currently well handled.

**Comment by mshuflin** [comment]
This results in a 500 Internal Server Error for me.

**Comment by georgegebbett** [comment]
Me too - [this](https://pastebin.com/3aP2RMz0) is the ld/json contained on that page. The `@Recipe` is in there, just where the scraper expects to find it... It really is infuriating how this data which is supposed to be standardised is in fact implemented completely randomly 😡

**Comment by mshuflin** [comment]
These sites are still giving me a error 500.  Anything  (logs or something) I can provide that would help?

**Comment by georgegebbett** [comment]
The contents of the JS console is always helpful - have you pulled the latest images?

**Comment by mshuflin** [comment]
```
{
    "statusCode": 500,
    "message": "Unable to extract Recipe metadata from provided url",
    "error": "Internal Server Error"
}
```
with this URL https://www.budgetbytes.com/weeknight-black-bean-chili/

**Comment by mshuflin** [comment]
Here are screenshots from the console.

<img width="600" alt="Screen Shot 2022-05-22 at 6 16 00 PM" src="https://user-images.githubusercontent.com/53985056/169690579-5a22b712-5e22-40ac-ba36-c059a3f730d1.png">
<img width="595" alt="Screen Shot 2022-05-22 at 6 15 51 PM" src="https://user-images.githubusercontent.com/53985056/169690582-7d66a8de-d7a7-4e33-8a14-638b17263b2c.png">
<img width="587" alt="Screen Shot 2022-05-22 at 6 15 39 PM" src="https://user-images.githubusercontent.com/53985056/169690584-f416c860-6215-4dc2-9b83-ca09bb90511e.png">

**Comment by georgegebbett** [comment]
I've just tested and this works fine for me 

![image](https://user-images.githubusercontent.com/35996500/169690712-74a2b01f-6ca3-477b-af29-0b762f858549.png)

I think this is likely an issue with you running an older version - it does not automatically update. What is in your `docker-compose.yml` file? Is it the same as the latest version in this repo?

**Comment by mshuflin** [comment]
Thanks for your patience. I got it working. My docker-compose.yml matches the one in the repo, but I did not have the latest image. Normally with dockerhub, portainer will pull the latest image when I recreate the container. But I had to pull the image, then recreate the container. working now!

**Comment by georgegebbett** [comment]
Amazing, glad you got it working! I'm about to do a release with a few enhancements so there will be another new image shortly - I've made changes to the way images are tagged which I'm hoping will make the whole thing play nicer with Portainer too. Out of interest, are you running RB as a Portainer Stack?

**Comment by mshuflin** [comment]
Yeah, I just paste the docker-compose.yml into the stack.
