### ISSUE TITLE
Adding a recipe to Grocy produces white page with white box

### ISSUE THREAD

**Issue by Camreyn** [georgegebbett/recipe-buddy#169]
![image](https://user-images.githubusercontent.com/40971318/195904441-0677953c-da3a-440b-85e3-d3b0e10a164b.png)

Clicking on ADD TO GROCY brings this page up with these errors when inspected.

Below is a screen grab of my grocy link, keep in mind both are the latest and grocy is running is Home Assistant.

![image](https://user-images.githubusercontent.com/40971318/195904648-e16e9494-26dc-45e1-bc7e-866bac88908c.png)

These are very standard configs with no edits to the configs.

Any help would be appreciated, thank you!

**Comment by georgegebbett** [comment]
All that CORS stuff is a bit weird - does it work if you install this chrome extension and enable it for that site? https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf

**Comment by georgegebbett** [comment]
A lot of the grocy communication happens in the browser because at the time I knew no better lol

**Comment by TheEndOfYoRHa** [comment]
Thank you for the swift reply, I was out for the weekend, that is on me, I apologize.

I installed the extension on firefox but I am still getting the same error.  Cool extension however, added to my tool-belt.

**Comment by creuzerm** [comment]
I was getting this error too. Somewhere in Grocy's instructions or one of the other tools that plug into Grocy there is the suggestion of setting a port so we can access Grocy direction and not route through HomeAssistant.

HomeAssitant->Settings->Addons->Grocy->Configuration->Network

Add port 9192 in that Network section. This doesn't appear to alter anything about the HomeAssistant integration, but now allows you to access Grocy directly, outside of HomeAssitant, by using that port. 

This looks to stop the CORS errors which I think are from trying to access Grocy on the HomeAssistant path from outside HomeAssistant. Different IPs is different domains, so CORS is doing it's job.

Now, I get a 500 error when I try to add a recipe, but that's something I haven't dug into to try to sort out, and likely for a different issue thread if somebody already started one.

**Comment by TheEndOfYoRHa** [comment]
@creuzerm I can do as you did with the port but when I feed the http://192.168.1.39:9192/api/ into Recipe Buddy, it says it cannot connect to grocy.  But if I go to that link in my web browser it brings me to the grocy api...

**Comment by creuzerm** [comment]
@TheEndOfYoRHa I am having the same issue as noted in https://github.com/georgegebbett/recipe-buddy/issues/256

**Comment by georgegebbett** [comment]
Hi all, apologies for the delay in getting back to you all on this - I have just released V2 which takes the Grocy URL as an env var into the Docker container and has a vastly simplified setup process and architecture - please have a go with this and open a new issue if you have further problems.
