### ISSUE TITLE
Add Recipe FAB is in the wrong place

### ISSUE THREAD

**Issue by georgegebbett** [georgegebbett/recipe-buddy#17]
The Add Recipe Floating Action Button is in the wrong place on the page - it should be at the bottom right but for some reason it is on the left, floating under the New Recipes paper.

**Comment by CloCkWeRX** [comment]
Just needs either a style="float: right" specifically on that control

![image](https://user-images.githubusercontent.com/365751/168453603-ecb0ce80-e74b-4783-8896-25bf3c81cf3a.png)

Or a container and some kind of  justify-content: flex-end;
