### ISSUE TITLE
HTTP 401 Unauthorised on new installation, fetching recipes

### ISSUE THREAD

**Issue by CloCkWeRX** [georgegebbett/recipe-buddy#19]
1. docker compose up 
2. create a user account
3. View web console/refresh

Unexpectedly; there's a HTTP 401 Unauthorised response from /recipes

![image](https://user-images.githubusercontent.com/365751/168453404-d62d0114-8ced-4367-b88e-82e25d84544a.png)

I would have thought that would simply be a HTTP 200 OK with an empty collection; OR if it's me having missed some configuration step, a visual warning.

**Comment by CloCkWeRX** [comment]
Ah, this is because I was in a half logged in state - creating the user did not log me in fully.

**Comment by georgegebbett** [comment]
The auth system is super hacky - I'm half minded to get rid of it entirely, but also mindful that someone might have this open to the internet (I do...). 

The password is stored in plaintext in the database and also occasionally sent in the clear from the server to the client. Definitely one to fix but lower on my priorities than actual recipe-related stuff.

I'll have a look at the initial setup one - that should be fairly easy to fix.

**Comment by georgegebbett** [comment]
This has been resolved (semi-satisfactorily) by #31
