### ISSUE TITLE
Better show logged in state, provide login/logout controls more prominently

### ISSUE THREAD

**Issue by CloCkWeRX** [georgegebbett/recipe-buddy#20]
![image](https://user-images.githubusercontent.com/365751/168453790-b89501c1-0888-45b4-b755-22973bdfbc50.png)

The UI in this state (#19) did not let me attempt login, and it was not obvious I was logged out after creating a user account.

As a user, I would probably have realised what was happening if there was a persistent login / logout control somewhere on the application layout (upper right hand side?).

It was only when I tried in a new private browsing window that I realised; and was able to login fully.

**Comment by georgegebbett** [comment]
There was a persistent login/out control at one point but I hated it so I got rid of it. 

I don't see a use case for making logging out easier to do - I'm not entirely sure why you would want to log out (Grocy will quite happily stay logged in permanently, as will Barcode Buddy)

I will definitely however make the redirect to the login screen work better, as that would alleviate this specific problem.
