### ISSUE TITLE
Help: Assist with connecting to Grocy

### ISSUE THREAD

**Issue by blowk** [georgegebbett/recipe-buddy#212]
Hi

I'm using Grocy in Home Assistant but I cannot connect it to Recipe Buddy.
I've created an API key.

What Grocy Base Url do I need to use? 
https://mydomainname.duckdns.org:portname/

This can be accessed from everywhere.

**Comment by georgegebbett** [comment]
Hi there!

You should just be able to use your standard grocy url - if you append /api to your url do you get the grocy api browser?

**Comment by blowk** [comment]
Hi

Thanks for your answer.

Yes, that's correct. When append /api, I go into the api browser, but when entering it in the Grocy settings, it cannot connect.
I'm running Recipe Buddy on localhost using docker.
In the console (chrome), I see an error when pressing 'update'-button but I don't know if this has something to do with it.

Error: PUT http://localhost:4000/api/users 401 (Unauthorized)

**Comment by georgegebbett** [comment]
Have you set up your user by going to the recipe buddy url /setup ?

**Comment by blowk** [comment]
I couldn't use this. There was only one user admin/demo.
When entering http://localhost:4000/setup > it redirect to http://localhost:4000/recipes (after login)

**Comment by blowk** [comment]
Thanks.
I found the problem.
When creating the user, the same user has to exist in Grocy too.

My mistake.

**Comment by georgegebbett** [comment]
Goodness me, I certainly didn't do that intentionally... One of these days I will do a complete rewrite of recipe buddy and all of these quirks will be gone!

**Comment by srvoets** [comment]
I cannot connect recipe buddy to grocy, username is same.  I can get to my https grocy url and api url, but when trying to connect through recipe buddy, no luck
