### ISSUE TITLE
What is the login password?

### ISSUE THREAD

**Issue by dbruynb** [georgegebbett/recipe-buddy#224]
Not sure if I have missed anything, but what is the login password?
My Grocy is setup on a ARM device, to I have to run recipe-buddy on a different machine.

**Comment by georgegebbett** [comment]
Hi there,

If you visit your recipe buddy url /setup you should be asked to choose a
user and password

**Comment by dbruynb** [comment]
When to the recipe buddy url /setup page, got the setup new user page. But nothing happens when I submit new credentials. Its as if it does not write it to the data base.

**Comment by georgegebbett** [comment]
That’s odd. Anything in the network tab of the dev tools when you hit
submit?

**Comment by dbruynb** [comment]
`Request URL: http://192.168.7.50:4000/api/users/setup
Request Method: POST
Status Code: 502 Bad Gateway
Remote Address: 192.168.7.50:4000
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 559
Content-Type: text/html
Date: Tue, 22 Nov 2022 04:55:23 GMT
Server: nginx/1.23.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-ZA,en-GB;q=0.9,en;q=0.8,en-US;q=0.7
Connection: keep-alive
Content-Length: 43
Content-Type: application/json
Host: 192.168.7.50:4000
Origin: http://192.168.7.50:4000
Referer: http://192.168.7.50:4000/setup
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.52`

I get a 502 bad gateway response

**Comment by georgegebbett** [comment]
That would suggest that the backend isn’t running - anything in the docker
logs to back that up?

**Comment by dbruynb** [comment]
I got it working, see this post.

https://www.reddit.com/r/grocy/comments/uismep/recipe_buddy_ready_for_testing/

`The issue was actually that the latest mongodb does not work in my system for some reason. Using image: mongo:4.4.6 fixed it for now.`

**Comment by georgegebbett** [comment]
Excellent! Glad you got it sorted.
