### ISSUE TITLE
Utilization of "yarn.lock" to lock down the dependencies in "app" dockerfile

### ISSUE THREAD

**Issue by inancdokurel** [georgegebbett/recipe-buddy#254]
Since you used yarn to develop the project, and a "yarn.lock" file exists, it is best practice to utilize it in the build process.

This would reduce the likelihood of deploying different versions of your dependencies from your development environment.

**Comment by georgegebbett** [comment]
Hi there - apologies for the delay on this one - I have just released V2 of Recipe Buddy which uses PNPM and has the lockfile used in the build :)
