### ISSUE TITLE
Not possible to connect to grocy

### ISSUE THREAD

**Issue by shootinggame82** [georgegebbett/recipe-buddy#256]
It's not possible to connect to grocy,
The url to my grocy is correct, and tried different api keys.

I use the same username and password as for grocy.

The backend log says when trying to connect to grocy:

TypeError: Cannot read properties of undefined (reading 'get')

And in the browser i get the following errors:

Failed to load resource: the server responded with a status of 401 (Unauthorized)

There is no problem with my Grocy, the api is working, im using api for other applications.
There is some problems in your system.

**Comment by crazycat36** [comment]
I too am having the same problem

**Comment by inancdokurel** [comment]
Had this issue, too. Fixed by clearing out the cookies for the site and creating a new username and password for recipe-buddy from /setup endpoint

**Comment by Saturo78** [comment]
I have the same problem.

**Comment by shootinggame82** [comment]
> Had this issue, too. Fixed by clearing out the cookies for the site and creating a new username and password for recipe-buddy from /setup endpoint

That is not possible, it's not possible to make another user.

**Comment by SKrywinski** [comment]
I have the same problem - can't create a new user from the frontend. But I can change the user accessing the mongodb; finding my way to get there (not very experienced with docker and docker-compose) I realized, that there are different networks interacting.
So I came across the idea that trying to access grocy, running on a raspberry in my local network from my notebook, recipe-buddy running in an docker-container on localhost could be a problem but I could dig into any deeper...
The error in my browser is 401 - incorrect grocy credentials (double- and triple-checked usernames, api-keys, ip-/addresses and so on), whereas docker-compose throws `LOG [UsersService] TypeError: Cannot read properties of undefined (reading 'get')` whenever I try to connect to grocy.

**Comment by creuzerm** [comment]
I am having the same issue. 
It appears like it could be a permissions thing talking to /api/users/ which is giving us the 401 Unauthorized as I am thinking the " @Request() request: RequestWithUserInfo" isn't being sent along maybe?

React and typescript aren't familiar to me, so I am struggling figuring the actual issue out.


I did write the two Grocy settings values directly to the mongodb and I have a connection to grocy now. My Settings page loads my Grocy URL and API Key, but when I click update, I still get 

PUT http://192.168.86.101:4000/api/users 401 (Unauthorized)
(anonymous) @ index.70f8cb40.js:45
uh @ index.70f8cb40.js:45
fh @ index.70f8cb40.js:45
request @ index.70f8cb40.js:45
(anonymous) @ index.70f8cb40.js:45
(anonymous) @ index.70f8cb40.js:44
b @ index.70f8cb40.js:163
b$ @ index.70f8cb40.js:84
w$ @ index.70f8cb40.js:84
S$ @ index.70f8cb40.js:84
vm @ index.70f8cb40.js:84
R0 @ index.70f8cb40.js:84
(anonymous) @ index.70f8cb40.js:84
yf @ index.70f8cb40.js:87
Qy @ index.70f8cb40.js:84
cu @ index.70f8cb40.js:84
Vp @ index.70f8cb40.js:84
B$ @ index.70f8cb40.js:84

**Comment by goapunk** [comment]
Got the same with the official docker images, interestingly it works when running the dev version :man_shrugging: Adding a recipe will return a 500 but it still shows up in grocy

**Comment by the-despised** [comment]
I believe it is axios that is the problem.  
in package.json i see 
`"axios" : "^1.2.0"`
however in my local, when I install I see axios: "1.3.2" has actually arrived.

So.. my theory is that 1.3.2 is running in dev mode, where as 1.2.0 is running in the build.  

Axios is the problem, error `LOG [UsersService] TypeError: Cannot read properties of undefined (reading 'get')` is 100% related to axios.

**Comment by ados8** [comment]
Was going to go with Mealie until I found this plugin for Grocy but it doesn't work. 😥
I have tired IP and domain, also with /api and /api/users.
My Grocy has an admin account with Buddy having the same admin username.
Is there a timeline to having this working, really want to use Grocy instead of Mealie.

**Comment by KyleStilkey** [comment]
I am also having trouble getting this to connect with Home Assistance installation of Grocy. I am able to connect my barcode scanner and apps to my phone without trouble, I just can't get this to communicate at all with Home Assistance without getting this error.

**Comment by dotnjet** [comment]
I too am having the same problem

**Comment by tynorton** [comment]
+1

**Comment by davidbeijinho** [comment]
+1

**Comment by VPAI-Bixal** [comment]
+1

**Comment by LeVraiRoiDHyrule** [comment]
Same problem here

**Comment by alkuzman** [comment]
+1
