### ISSUE TITLE
White page when clicking on the import to grocy button

### ISSUE THREAD

**Issue by bonelifer** [georgegebbett/recipe-buddy#41]
White page when clicking on the import to grocy button.

**Comment by bonelifer** [comment]
[backend.log](https://github.com/georgegebbett/recipe-buddy/files/9146656/backend.log)
[frontend.log](https://github.com/georgegebbett/recipe-buddy/files/9146657/frontend.log)
[mongo.log](https://github.com/georgegebbett/recipe-buddy/files/9146658/mongo.log)

**Comment by georgegebbett** [comment]
Hi there, thanks for opening this issue!

The logs don't seem to suggest any requests are making it to the backend... Are you able to import recipes into recipe buddy itself and select the ingredients?

**Comment by bonelifer** [comment]
They import fine into Recipe buddy..

**Comment by georgegebbett** [comment]
I have a feeling your issues are somehow interrelated - what happens in the network tab of chrome when you try to import the recipe to grocy?

**Comment by bonelifer** [comment]
I'm using Linuxserver.io's container, if that info helps: https://hub.docker.com/r/linuxserver/grocy

**Comment by bonelifer** [comment]
crossposted. Thanks for getting back to me. I've since decided on Tandoor Recipes as Grocy itself is just more than what I need. In that regard it feels to heavy for what I want, ie collect and use online recipes at home.  I hope your project continued success. You may close this at your discretion or leave it open incase others are having similar problems.

**Comment by tfergy** [comment]
I am having the same issue.  I have added a handful of recipes through recipe-buddy, however, when I click add to grocy, I get a white page and have to click the back key then refresh.  In addition to this happening, in the settings page under Grocy settings, it shows the status "Cannot connect to grocy".  When I click update it shows connected.  If I click on Recipes on the left, then click back to settings the status is back to "Cannot connect to grocy".

**Comment by georgegebbett** [comment]
The white screen issue is very odd - I've been incredibly busy with work and haven't had a chance to look into it but I will do. 

The other issue with the grocy settings screen is a known issue - it is on my list to fix

**Comment by georgegebbett** [comment]
Just having a look into this - if you open the Chrome developer tools and select the network tab and then add a recipe, what do you see?

**Comment by thesuperben** [comment]
Hey George,

Same issue here. Output from console immediately after selecting Add to Grocy and receiving a blank white screen below. URL redirects to localhost:4000/recipes/62e26d0203c05dbcef4567b3.

![image](https://user-images.githubusercontent.com/31153797/181492311-9ad98eb8-81ac-41c9-9a39-7444a0896c77.png)

**Comment by georgegebbett** [comment]
Thank you - that narrows things down - I have been unable to reproduce this today which is odd - would you be able to post the content of the network tab?

**Comment by thesuperben** [comment]
What do you need exactly? It looks like I'm not really seeing anything in the network tab.

**Comment by thesuperben** [comment]
> 

This seems to have resolved itself for me now. Unsure what changed other than adding more products to Grocy.

**Comment by tfergy** [comment]
Still have the same issue.  This is the output from console after adding recipe to Grocy:
![Screenshot - 7_28_2022 , 8_07_44 PM](https://user-images.githubusercontent.com/65680442/181662910-9cf16de1-9f05-4357-a182-6de377b0ac33.png)

**Comment by oregapam** [comment]
Hello,
I have same problem.

**Comment by TripleE-0** [comment]
Hi @georgegebbett  here is my network tab when I attempt to add a recipe to grocy. I am also using the linuxserver.io container for grocy. 
![image](https://user-images.githubusercontent.com/956828/183293062-9bd7e225-f463-4fd5-9c6d-f0e66b6fa4bd.png)

**Comment by georgegebbett** [comment]
Thank you for this - I have a feeling I know why this is happening now but will investigate when I am back in front of my computer tonight

**Comment by georgegebbett** [comment]
I have still been unable to reproduce the issue - but I think I have found where it is coming from. I have done a release which should be published to the container registries imminently. If you could pull the fresh image, and attempt to do the same thing which leads to the issue, hopefully you should see an error message in the actual browser. I haven't actually implemented a fix yet because I'm not sure what I'm fixing, but please let me know if you see different behaviour and then I will know I have found the problematic code and can set about fixing it!

**Comment by TripleE-0** [comment]
I updated the containers and attempted again. Still have a white page, no error message there but I saw some different messages in the console. 
![image](https://user-images.githubusercontent.com/956828/183309714-b75fb8c1-8948-46c0-887e-176a679f4003.png)
![image](https://user-images.githubusercontent.com/956828/183309789-855c98ab-ed70-4982-a126-ca6350a56f61.png)
Hopefully this helps!

**Comment by georgegebbett** [comment]
Okay - I think I'm looking in the wrong place in that case. Is the page entirely white or do you have some of the UI visible? Just also checking that you have products and quantity units set up in Grocy, and all your products have quantity units associated with them?

**Comment by TripleE-0** [comment]
I am guessing that we are suppose to see something like this screenshot? This screen flashes by very quickly and I was only able to grab one frame of it visible when I took a quick video. 
![image](https://user-images.githubusercontent.com/956828/183311332-791670c3-e3a3-4481-a111-4ab34a2a68f0.png)

I do not have products imported yet... Now that you ask, it would make a lot of sense why you would need products in Grocy before importing recipes... 
I do have quantity units in Grocy though. 
This is the screen that I see after. 
![image](https://user-images.githubusercontent.com/956828/183311378-8bd088d5-f119-45e1-98bc-cb04e1343602.png)

**Comment by georgegebbett** [comment]
Okay, in this case I'm fairly sure I know what the issue is, and it likely stems from your lack of products (the frontend is crashing when trying to iterate over a list of products that it doesn't expect to be empty). I can fix this but a workaround should be to add at least one product to grocy. At any rate you wouldn't be able to import recipes before adding products as each recipe ingredient needs to be associated with a grocy product for the import to succeed.

**Comment by TripleE-0** [comment]
I can confirm, as soon as I made a test product I was able to see the actual page. 
![image](https://user-images.githubusercontent.com/956828/183529630-0b117553-0cfe-4db6-adb9-096837a70a71.png)

**Comment by georgegebbett** [comment]
Amazing - the bug is officially located! I'll fix it shortly and make a new release!

**Comment by georgegebbett** [comment]
I haven't been able to test this as the test Grocy domain seems to have gone down, however I believe it should now be fixed
