### ISSUE TITLE
Won't accept localhost as url

### ISSUE THREAD

**Issue by bonelifer** [georgegebbett/recipe-buddy#42]
It Won't accept localhost as url, have to use the IP address instead,

`http://192.168.1.80:4002`

**Comment by georgegebbett** [comment]
Strange that it's port 4002 - have you changed the docker compose file to move away from port 4000?

**Comment by bonelifer** [comment]
Yes. Already had Dashy on that port.

**Comment by bonelifer** [comment]
Thanks for getting back to me. I've since decided on Tandoor Recipes as Grocy itself is just more than what I need. In that regard it feels to heavy for what I want, ie collect and use online recipes at home.  I hope your project continued success. You may close this at your discretion or leave it open incase others are having similar problems.
