### ISSUE TITLE
"docker-compose up" just not working

### ISSUE THREAD

**Issue by ajperez74** [georgegebbett/recipe-buddy#431]
As simple as the installation is, on my bash shell I got the message that the command `docker-compose up` is unknown.  
It seems I am doing something wrong here, but I followed the instructions. I installed the script on a unraid share.
Thanks for your support.

**Comment by teejo75** [comment]
Depending on the version of Docker, the command might be `docker compose up` no hypen. Alternatively you would need to install docker-compose.

**Comment by georgegebbett** [comment]
Hi all - apologies for the delay on this - V2 has just been released with no dependency on Docker Compose, so should solve this!
