### ISSUE TITLE
Can't connect to Docker Grocy backend

### ISSUE THREAD

**Issue by redfive2012** [georgegebbett/recipe-buddy#445]
I'm running Grocy as a standalone Docker stack, with the Recipe Buddy containers added to it. Apparently, when not running as part of Home Assistant, the Grocy backend exposes port *9000* rather than *4000*. I'm unsure how to change either what port Recipe Buddy uses to communicate with the Grocy backend inside its Docker container, or to change what port Grocy's backend uses inside its Docker container.

**Comment by georgegebbett** [comment]
Hi there, apologies for the delay in getting back to you on this - I have just released V2 which takes the Grocy URL as an env var into the Docker container - this should allow for easier setup but if you have a go and still run into issues please let me know and I will look into it.
