### ISSUE TITLE
Unable to create new user 405 not allowed

### ISSUE THREAD

**Issue by Zipties** [georgegebbett/recipe-buddy#446]
I am able to load the create a user screen at first time setup, but when pressing submit nothing happens. Bringing up the dev con shows it is being rejected with a 405 

<details>
<summary>Details</summary>

`index.70f8cb40.js:163 $e..{message: 'Request failed with status code 405', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {...}, request: XMLHttpRequest,.....}
index.70f8cb40.js:45 
        
        
        POST http://192.168.45.10:4000/api/users/setup 405 (Not Allowed)
(anonymous) @ index.70f8cb40.js:45
uh @ index.70f8cb40.js:45
fh @ index.70f8cb40.js:45
request @ index.70f8cb40.js:45
(anonymous) @ index.70f8cb40.js:45
(anonymous) @ index.70f8cb40.js:44
i @ index.70f8cb40.js:163
b$ @ index.70f8cb40.js:84
w$ @ index.70f8cb40.js:84
S$ @ index.70f8cb40.js:84
vm @ index.70f8cb40.js:84
R0 @ index.70f8cb40.js:84
(anonymous) @ index.70f8cb40.js:84
yf @ index.70f8cb40.js:87
Qy @ index.70f8cb40.js:84
cu @ index.70f8cb40.js:84
Vp @ index.70f8cb40.js:84
B$ @ index.70f8cb40.js:84
index.70f8cb40.js:163 $e..{message: 'Request failed with status code 405', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {...}, request: XMLHttpRequest,.....}code: "ERR_BAD_REQUEST"config: {transitional: {...}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ..,.....}message: "Request failed with status code 405"name: "AxiosError"request: XMLHttpRequest..{onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload,.....}response: config: {transitional: {...}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ..,.....}data: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.23.2</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n"headers: pn..{connection: 'keep-alive', content-length: '559', content-type: 'text/html', date: 'Thu, 18 May 2023 16:01:37 GMT', server: 'nginx/1.23.2',.....}connection: "keep-alive"content-length: "559"content-type: "text/html"date: "Thu, 18 May 2023 16:01:37 GMT"server: "nginx/1.23.2"Symbol(defaults): null[[Prototype]]: Objectrequest: XMLHttpRequest..{onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload,.....}status: 405statusText: "Not Allowed"[[Prototype]]: Objectstack: "AxiosError: Request failed with status code 405\n    at UC (http://192.168.45.10:4000/assets/index.70f8cb40.js:44:11294)\n    at XMLHttpRequest.d (http://192.168.45.10:4000/assets/index.70f8cb40.js:45:4224)"[[Prototype]]: Error
`

</details>

EditL Disregard, the latest dev build does not have this issue

**Comment by georgegebbett** [comment]
Hi all, apologies for the delay in getting back to you all on this - I have just released V2 which takes the Grocy URL as an env var into the Docker container and has a vastly simplified setup process and architecture - please have a go with this and open a new issue if you have further problems.
