### ISSUE TITLE
How do I do if I don't want my containers to be named "frontend" "backend" ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [georgegebbett/recipe-buddy#449]
Hi,

I already have containers named "frontend" and "backend" for other services, so they have to be named differently. I named them recipebuddy-frontend, recipebuddy-backend, recipebuddy-mongo.
But now how do I do to get them to connect together ? Most multi-container services have env variables you can set to say what is the db host, the backend host...
I found no mention of that in recipebuddy docs. How can I do that ?

Thanks in advance for any answer.

**Comment by TheCDC** [comment]
I have this question as well

**Comment by vagabond666** [comment]
I'm slightly perplexed, because both grocy and this add-on both seem to be hardcoded to use backend as a hostname, so surely enough people should have run into this issue that it'd be resolved now, or at least someone would have turned up and gone "Why are you using docker like that? Do this and it'll fix the issue"

**Comment by LeVraiRoiDHyrule** [comment]
I am too. But it's probably just because this repo is not very active. I hope there will be a setting for that one day though, because I can't deploy recipe-buddy until then.

**Comment by redfive2012** [comment]
I think you can work around the issue by running all the recipe-buddy and grocy containers on their own docker virtual network, separate from other containers. If you run grocy and recipe-buddy via docker-compose, it usually sets up a new docker network for that grouping (Portainer calls them Stacks).

**Comment by georgegebbett** [comment]
Hi all - apologies for the delay on this one - I've just released V2 of Recipe Buddy which is deployed using just one container which should allow you to get round this problem as you can call it whatever you like :)
