### ISSUE TITLE
Cannot connect to Grocy

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [georgegebbett/recipe-buddy#450]
Hi,

I can't connect to grocy from recipe-buddy, I have the following error:
`[Nest] 19  - 07/04/2023, 2:43:13 PM     LOG [UsersService] TypeError: Cannot read properties of undefined (reading 'get')`

The grocy URL and API are correct. Grocy is up and running.
What am I supposed to do ?

Thanks in advance for any answer

**Comment by johnmoxon** [comment]
I also receive this issue when connecting to Grocy. When setting the grocy Base URL and API key (correctly) the following request and response are observed

**Request headers**
```
Request URL: http://192.168.86.10:4000/api/users
Request Method: PUT
Status Code: 401 Unauthorized
Remote Address: {{RECIPE_BUDDY_IP}}:4000
Referrer Policy: strict-origin-when-cross-origin
```

**Request payload**
`{"grocyBaseUrl":"{{GROCY_URL}}","grocyApiKey":"{{GROCY_API_KEY}}"}`

**Response**
`{"statusCode":401,"message":"Incorrect Grocy Credentials"}`

**Comment by soylant** [comment]
I also recive this error, is this project dead??

**Comment by TheCDC** [comment]
@soylant The last update was in December which to me isn't that long ago fora hobby project. I'm hopeful although this issue seems strange to have popped up.

**Comment by TheCDC** [comment]
I get an error in the browser console in Firefox when clicking "add to grocy". I don't know if that the source of the showstopping bug.


    Uncaught (in promise) TypeError: T.sort is not a function
    K http://192.168.0.110:5001/assets/index.70f8cb40.js:163
    $ http://192.168.0.110:5001/assets/index.70f8cb40.js:163
    t_ http://192.168.0.110:5001/assets/index.70f8cb40.js:163
    xc http://192.168.0.110:5001/assets/index.70f8cb40.js:87
    Vo http://192.168.0.110:5001/assets/index.70f8cb40.js:87
    tP http://192.168.0.110:5001/assets/index.70f8cb40.js:87
    E http://192.168.0.110:5001/assets/index.70f8cb40.js:72
    X http://192.168.0.110:5001/assets/index.70f8cb40.js:72
    EventHandlerNonNull* http://192.168.0.110:5001/assets/index.70f8cb40.js:72
    <anonymous> http://192.168.0.110:5001/assets/index.70f8cb40.js:72


Clicking on line 163 shows what looks like a minified version of the frontend code and this portion contains what my browser debug console underlined as being in error

`await Ne.get(`${i}${r}`,{headers:{"GROCY-API-KEY":a}}),N=T.sort((_,B)=>{const L=_.name.toUpperCase(),J=B.name.toUpperCase();return L<J?-1:L>J?1:0});return p(N),w(!0),T}`

**Comment by TheCDC** [comment]
I think I've made progress on this issue. I pulled the repo main and built the containers locally and Recipe Buddy can authenticate with the API on both my existing private global instance of Grocy and a new install of the desktop app.

All I did was use this custom docker compose file form the repo root.

    version: "3.4"

    services:
      mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
          - mongo_db:/data/db

      backend:
        depends_on:
          - "mongo"
        build:
          context: ./api
          dockerfile: Dockerfile

      frontend:
        ports:
          - "4000:80"
        depends_on:
          - "backend"
        build:
          context: app
          dockerfile: Dockerfile

    volumes:
      mongo_db:



@georgegebbett I think there may be an issue with the latest public docker images of Recipe Buddy because the repo as-is right now works fine.

**Comment by soylant** [comment]
If i download the master and change the docker-compose.yaml i get the following error on install error An unexpected error occurred: "https://registry.yarnpkg.com/axios/-/axios-0.26.1.tgz: ETIMEDOUT".

**Comment by TheCDC** [comment]
@soylant That error may be ephemeral and due to network conditions. Did you retry the process?

**Comment by soylant** [comment]
I did what TheCDC did and running it from the master, so happy everything is running fine :-)

**Comment by KyleStilkey** [comment]
Thanks @TheCDC your post helped me, I updated my docker-compose.yml with your code and installed and it took a little bit but it's up and running.

Placed API from Grocy in and URL in (I'm using DuckDNS so I put my websites URL from Home Assistant when I click on Grocy and it connected without any issues.

**Comment by TheQuickestFox** [comment]
> @georgegebbett Thanks! I am happy to wait for the rewrite. I'm running Recipe Buddy off of `master` right now and it works fine so I'm not actually sure what the problem is.

Just to confirm, you are just running the as is unmodified master branch, or the master branch with the proposed changes to the docker compose file?

I am having trouble implementing the changes and getting it to deploy as a stack in Portainer, so I am just confirming my basic assumption that it's still needed.

**Comment by natevns08** [comment]
> I think I've made progress on this issue. I pulled the repo main and built the containers locally and Recipe Buddy can authenticate with the API on both my existing private global instance of Grocy and a new install of the desktop app.
> 
> All I did was use this custom docker compose file form the repo root.
> 
> ```
> version: "3.4"
> 
> services:
>   mongo:
>     image: mongo
>     restart: always
>     environment:
>       MONGO_INITDB_ROOT_USERNAME: root
>       MONGO_INITDB_ROOT_PASSWORD: root
>     volumes:
>       - mongo_db:/data/db
> 
>   backend:
>     depends_on:
>       - "mongo"
>     build:
>       context: ./api
>       dockerfile: Dockerfile
> 
>   frontend:
>     ports:
>       - "4000:80"
>     depends_on:
>       - "backend"
>     build:
>       context: app
>       dockerfile: Dockerfile
> 
> volumes:
>   mongo_db:
> ```
> 
> @georgegebbett I think there may be an issue with the latest public docker images of Recipe Buddy because the repo as-is right now works fine.

This is the ticket, thank you @TheCDC

**Comment by georgegebbett** [comment]
Hi all, apologies for the delay in getting back to you all on this - I have just released V2 which takes the Grocy URL as an env var into the Docker container and has a vastly simplified setup process and architecture - please have a go with this and open a new issue if you have further problems.
