### ISSUE TITLE
Cannot connect to Grocy

### ISSUE THREAD

**Issue by StefanoGiu** [georgegebbett/recipe-buddy#462]
It worked like a charm to scrape the webpage and add the receipt, but then, I'm not able to connect to Grocy, even if I put the proper Grocy URL and api key. What's wrong?

**Comment by georgegebbett** [comment]
Hi all, apologies for the delay in getting back to you all on this - I have just released V2 which takes the Grocy URL as an env var into the Docker container and has a vastly simplified setup process and architecture - please have a go with this and open a new issue if you have further problems.
