### ISSUE TITLE
can not connect to Grocy

### ISSUE THREAD

**Issue by ioannis2** [georgegebbett/recipe-buddy#463]
Object { stack: "$e@http://192.168.80.31:8183/assets/index.70f8cb40.js:44:5778\nUC@http://192.168.80.31:8183/assets/index.70f8cb40.js:44:11294
\nd@http://192.168.80.31:8183/assets/index.70f8cb40.js:45:4226\n", message: "Request failed with status code 500", name: "AxiosError", 
code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…} }

**Comment by georgegebbett** [comment]
Hi all, apologies for the delay in getting back to you all on this - I have just released V2 which takes the Grocy URL as an env var into the Docker container and has a vastly simplified setup process and architecture - please have a go with this and open a new issue if you have further problems.
