### ISSUE TITLE
Integrity constraint violation on sending recipe to grocy

### ISSUE THREAD

**Issue by mbeutelspacher** [georgegebbett/recipe-buddy#464]
Whenever I actually send the recipe to grocy I get the following error in the frontend:
![image](https://github.com/georgegebbett/recipe-buddy/assets/19970219/fc5b39cc-e4e3-4f6f-867d-ccda643ffe69)
and the following error in the backend's logs:

```
data: {
      error_message: 'SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: recipes_pos.recipe_id'
    }
```

**Comment by georgegebbett** [comment]
Apologies for the delay on this one - you shouldn't see this in v2
