### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when try to open website

### ISSUE THREAD

**Issue by budda85** [georgegebbett/recipe-buddy#475]
Hey,
i try to set up the docker conainter on my NAS.
But when i try to open the website there comes an Error with "Too many redirects"
This is the URL after loading.
![grafik](https://github.com/georgegebbett/recipe-buddy/assets/20152200/48de5ff5-e63f-49f4-a356-8a11b621c3bd)

Log:
> grocy-importer
date,stream,content
2024/04/04 10:47:57,stdout, ✓ Ready in 1471ms
2024/04/04 10:47:57,stdout,
2024/04/04 10:47:57,stdout,   - Network:      http://0.0.0.0:3000
2024/04/04 10:47:57,stdout,   - Local:        http://localhost:3000
2024/04/04 10:47:57,stdout,   ▲ Next.js 14.0.3
2024/04/04 10:47:55,stdout,
2024/04/04 10:47:55,stdout,> node migrations/drizzle-migrate.mjs
2024/04/04 10:47:55,stdout,> recipe-buddy-v2@0.1.0 db:migrate
2024/04/04 10:47:55,stdout,

Docker:
> docker run \
 -p 3005:3000 \
 -v rb_data:/home/node/app/data \
 --env GROCY_API_KEY=Pf5ovbdzxxxxxxxxxX9FJlP0I1 \
 --env GROCY_BASE_URL=grocy.xxxxxxx.com \
 --env NEXTAUTH_SECRET=Pf5ovbdzxxxxxxxxxX9FJlP0I1 \
 --env NEXTAUTH_URL=http://localhost:3005 \
 ghcr.io/georgegebbett/recipe-buddy

Someone some Tips?

**Comment by budda85** [comment]
Ahh, sorry for that issue.
It is a problem with the Proxy on my work. At home it does work!

**Comment by georgegebbett** [comment]
No worries - if you have an external url for the RB instance it is best to use this as your next auth url rather than the localhost one :)
