### ISSUE TITLE
Feature Request - Groups & Notes

### ISSUE THREAD

**Issue by Bovive** [georgegebbett/recipe-buddy#476]
If it is possible, I would find it very handy to be able to add notes and a group to the ingredients when importing them. For example, if something says that it is "minced", I currently have to remember it or go back and look it up to manually add the note to the ingredient. Awesome stuff, I am very much enjoying using this app, thanks!

**Comment by georgegebbett** [comment]
Ooh that is a good idea - have thrown this together and will be in the next release :)

**Comment by georgegebbett** [comment]
The release is going out now and pulling the latest Docker image (in like 15 mins when it's done building) will get you the new version with this functionality added :)
