### ISSUE TITLE
Recipes in Grocy not visible in RecipeBuddy 

### ISSUE THREAD

**Issue by TheQuickestFox** [georgegebbett/recipe-buddy#477]
After creating a recipe in RB, then syncing it into Grocy, it becomes invisible to RB. 

Not sure if this is intended behavior yet since this is new to me and a new version of RB, but the UI seems to imply that the recipes should remain editable with RB even after they're created in Grocy.

Grocy v4.2.0
RB build v2.0.1 Latest.
![image](https://github.com/georgegebbett/recipe-buddy/assets/79387832/9d140a63-06a3-4d8a-b4b0-66aefb0e8eb5)

Single recipe in Grocy, created through RB

![image](https://github.com/georgegebbett/recipe-buddy/assets/79387832/168be610-b193-4b95-a9c0-984be5ac662f)

**Comment by georgegebbett** [comment]
Hi there - yes this is intended behaviour - RB's purpose is to ease the pain of manually adding recipes to Grocy, and once they are there the recipe is removed from RB as it is now in Grocy and RB has served its purpose :)
