### ISSUE TITLE
Toast error "Something went wrong UNAUTHORIZED"

### ISSUE THREAD

**Issue by jaymemaurice** [georgegebbett/recipe-buddy#480]
Sorry I'm green.

Tried to launch the container, with what I thought were the right docker env variables but when I try to scrape a recipe I get a generic error toast error. "Something went wrong UNAUTHORIZED" What is unauthorized?

Is it that it can't get to grocy? Note I'm using the HA addon for Grocy and am trying 
--env GROCY_BASE_URL=http://192.168.2.45:8123/hassio/ingress/a0d7b954_grocy/ 

Is it allrecipees and others giving the 401?

my browser URL for recipe buddy is at http://192.168.2.45:3005/recipes

{
    "input": {
        "url": "https://www.allrecipes.com/recipe/20144/banana-banana-bread/"
    },
    "result": {
        "meta": {
            "response": {}
        },
        "shape": {
            "message": "UNAUTHORIZED",
            "code": -32001,
            "data": {
                "code": "UNAUTHORIZED",
                "httpStatus": 401,
                "path": "recipe.scrape",
                "zodError": null
            }
        },
        "data": {
            "code": "UNAUTHORIZED",
            "httpStatus": 401,
            "path": "recipe.scrape",
            "zodError": null
        },
        "name": "TRPCClientError"
    },
    "elapsedMs": 30,
    "context": {}
}

**Comment by jaymemaurice** [comment]
Ah so it seems it timed out the login or something...
and when I try to login it sends to the wrong callback url:
https://htp//localhost:3005/callback/credentials

despite the correct callback url appearing to be encoded in the login page URI http://192.168.2.45:3005/api/auth/signin?callbackUrl=**http%3A%2F%2F192.168.2.45%3A3005%2F**

**Comment by jaymemaurice** [comment]
I had NEXTAUTH_URL URL set incorrectly.

**Comment by jaymemaurice** [comment]
<port>/callback/credentials as reachable from the container. In my case I had htp// in there 

Turns out I had many issues with trying to use Grocy homeassistant add on from ingress and eventually gave the addon its own port so barcode scanner and other stuff could work.

**Comment by justbest23** [comment]
Thanks for the speedy reply!

I'm not understanding, sorry.

My config is as follows, running inside a docker-compose.yml along with a bunch of other services.

`  recipe-buddy:
    image: ghcr.io/georgegebbett/recipe-buddy
    ports:
      - "3005:3000"
    volumes:
      - rb_data:/home/node/app/data
    environment:
      GROCY_API_KEY: <API Key Here>
      GROCY_BASE_URL: http://homeassistant.home:8123/hassio/ingress/a0d7b954_grocy
      NEXTAUTH_SECRET: <secret here>
      NEXTAUTH_URL: http://192.168.0.203:3005
    container_name: "recipe-buddy"`


My Home Assistant instance is at `192.168.0.18` or at the `homeassistant.home' url above.

I don't know what is supposed to go where?
