### ISSUE TITLE
I'm unable to login

### ISSUE THREAD

**Issue by TriplePlay73** [georgegebbett/recipe-buddy#63]
Everything went well until I got to the login. LOL, what is the username & Password?

I really appreciate any help you can provide

**Comment by georgegebbett** [comment]
Hello!

There is no default username and password - if you navigate to /setup you should be able to set the user and password. If you have already inadvertently set it it is stored in plaintext in the db so you should be able to pull it out of there!

**Comment by georgegebbett** [comment]
I'm guessing this is now sorted? Feel free to reopen if not!

**Comment by adamcullen** [comment]
Hi, I've just followed the V2 instructions in the readme and got the docker site up and running. I've inserted my Grocy url and api, but when I go to localhost:3005 there's a recipe buddy banner at the top of the page and a sign in button. clicking on the sign in button takes me to a page that asks for username and password.  At first I thought this might be the username and password for the user attached to the Grocy api, but it didn't work - so I figure this is a username and login into the database attached in recipe-buddy.

Are you able to help me out please?
![Capture](https://github.com/georgegebbett/recipe-buddy/assets/23371950/86b4c8cd-bec4-4d1e-8b0b-df9e0391a285)

cheers
Adam
