### ISSUE TITLE
copy paste for recipes behind login walls?

### ISSUE THREAD

**Issue by cranky-coder** [georgegebbett/recipe-buddy#92]
Feature Request:

I have a bunch of recipes I use from themealprepmanual.com site and they are behind a login.  Is there a way to copy and paste into recipe buddy that will parse the copied/pasted values as a recipe?

**Comment by georgegebbett** [comment]
Hi there! At the moment this is not something I am planning on implementing as the recipes are currently scraped from structured data, and there is currently no way of parsing text into a recipe - however if you would like to have a crack at it please open up a PR :)
